# build.nixpacks.toml
[phases.setup]
nixPkgs = ['python3', 'python311Packages.virtualenv', 'openssl']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip',
  '/opt/venv/bin/pip install -r requirements.txt'
]
